### ISSUE TITLE
Please use a monospace font for the console

### ISSUE THREAD

**Issue by JodiTheTigger** [Celtoys/Remotery#122]
My pretty console art is ruined when remotery isn't using a mono-spaced font for the console output.

**Comment by dwilliamson** [comment]
While I understand the desire for this it unfortunately cuts the amount of readable text horizontally by almost half. The best I can come up with is:

```css
font-size: 8pt;
font-family: Lucida Console, Courier New, Courier, monospace;
```
There are obviously better fonts out there but last thing I want to do is depend on a remote font file.

You can play around yourself with the CSS code [here](https://github.com/Celtoys/Remotery/blob/master/vis/Styles/Remotery.css#L64). Let me know if you find something of equal width and legible.

Meanwhile, keeping this open because I will switch to monospace once the tab view has been ported over,

**Comment by JodiTheTigger** [comment]
I strictly enforce 80 columns for my console output so I don't hit the horizontal text width limit myself, however I know that in most places this is a luxury people don't have. For my project I've just edited the CSS back to monospace.

Other possible solutions (some tongue in cheek):
* horizontal scroll bar
* word wrapping
* UI selectable mono/normal font button.
* tiny weeny font sizes
* buy a bigger monitor
