### ISSUE TITLE
are there plans to integrate DirectX12 into remotery ?

### ISSUE THREAD

**Issue by arjankuijpers** [Celtoys/Remotery#125]

**Comment by dwilliamson** [comment]
Not from me, no as I'm not currently working with DX12.

@neilogd has a working implementation but hasn't pushed anything yet: https://twitter.com/neilogd/status/902114802528468992 (https://github.com/neilogd/Remotery)

Others may have working implementations, also.

**Comment by neilogd** [comment]
I did start working on it, but hit some annoying road blocks.

I'll try clean up some of the initial work I started and get it committed. The road block I hit was an obscure crash when trying to use the DX12 C API. I started leaning on Get/SetPrivateData to tie Remotery constructs to command queues, rather than the calling thread to get timelines per-queue.
