### ISSUE TITLE
Threads not showing up

### ISSUE THREAD

**Issue by delscorcho** [Celtoys/Remotery#141]
Anyone know why threads wouldn't show up? In a simple test with one thread pushing timers, I only see the Remotery thread in the UI.

**Comment by delscorcho** [comment]
Yep, and the sample is working as advertised.

My actual app is relatively simple - one application thread - but that thread is extremely busy. Eventually the thread shows up in the Remotery UI, but the UI is very late to reflect any of the data. It's almost as if the Remotery thread is starved, but I can see up to date data for the Remotery thread's own profile timers. Perhaps I'll play with some of the remotery settings or instrument further to see what's happening.

**Comment by dwilliamson** [comment]
If the Remotery thread is working away then it suggests the reporting thread is doing fine. Possibilities:

* The root sample needs to be closed before any data is sent from a thread to the viewer.
* You're sending so many samples that it's overflowing the internal queues and discarding them (Remotery chooses to do this rather than block your code and affect your timing). That they show up later could mean you're sending just the right amount. Try upping the queue size and decreasing the thread sleep time.
* Some logic bug in the viewer. I have seen lots of data take a while to show up in the viewer at times and it was possibly linked to communicating the name database. There seems to be a lot of traffic communicating these names that could definitely be optimised.

**Comment by dwilliamson** [comment]
Great, glad you got it sorted. Thanks for the comments!
