### ISSUE TITLE
Remotery build error under windows10

### ISSUE THREAD

**Issue by BartolomeyKant** [Celtoys/Remotery#221]
I just downloaded last Remotery release and try to compile it.

```
clang.exe -c -o Remotery.o -I ..\lib ..\lib\Remotery.c
```

And got this error:

```
..\lib\Remotery.c:5574:18: error: Unable to lookup field reference!
        mov [edi].processorIndex, eax
                 ^
1 error generated.
```

I don't know assembler well and never met using field references like this.

**Comment by dwilliamson** [comment]
Remotery does not completely build on the triple Clang/Windows/x86.

You have some options, though:

* Change your build target to x64.
* Modify `Remotery.c` so that `RMT_ENABLE_THREAD_SAMPLER` is not defined (alternatively move it into the header file along with the rest of the compile options and submit a PR).
* Convert the inline x86 ASM code to Clang syntax.
