### ISSUE TITLE
Late-starting threads have offset time reporting.

### ISSUE THREAD

**Issue by bengarney** [Celtoys/Remotery#37]
The zero-base for sample starts is set when the first sample tree on a thread is created.

This can happen arbitrarily late (imagine spinning up a worker thread). It also introduces error even when you start threads at about the same time.

All threads should have useconds reported on the same timebase with zero having the same meaning on every thread.

**Comment by bengarney** [comment]
It looks like you could keep a "starting time" QPC measurement and use that as the basis value rather than init, and all would be well. (Just a theory, not tested.)

**Comment by dwilliamson** [comment]
Years ago we used to have issues with QPC across multiple cores so I tried to avoid the issue when starting the library off. My code isn't really a work-around, it's probably the equivalent of sticking my fingers in my ears and going "la la la" :) (e.g. it won't work if a thread crosses over to another core)

I think the simplest solution is to store the usTimer instance in the Remotery object itself instead of the thread sampler - that would get all threads nicely in sync (assuming your hardware/OS combination doesn't subvert this).

I'm off on holiday for the weekend but can look into it when I get back.

**Comment by dwilliamson** [comment]
Note that each new session of the viewer would then need to record the first incoming timestamp to display samples from the beginning of the timeline.

**Comment by bengarney** [comment]
Latest wisdom re: QPC is that "only systems with bad drivers/hardware" have issues across cores... YMMV but it's not clear to me there's any better option. (Maybe round first sample to nearest ms/16ms and use alternate query? Or do both for sanity checking?)

**Comment by bengarney** [comment]
Awesome, thanks! We did almost the same fix locally.
