### ISSUE TITLE
Samples not combined?

### ISSUE THREAD

**Issue by jswigart** [Celtoys/Remotery#44]
Are the samples supposed to be condensed into a single entry with a # calls sort of tracking?

It didn't seem right to be that all the samples called within a loop would be separate like this.

![image](https://cloud.githubusercontent.com/assets/4065267/7211711/96874986-e523-11e4-80c2-04c85c416138.png)

**Comment by Celtoys** [comment]
No, all samples are unique and don't collapse or recognise recursion. By default, aggregating samples is not optimal behaviour for an instrumenting sampler and Remotery's first goal is to interfere with your timings as little as possible.

However, this goal is not good enough on its own. Remotery needs the ability to do what you ask and the place to insert that feature is here: https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L3408

In short, this needs to happen:

* Public API needs to support sample flags or different function calls for samples that aggregate.
* When pushing a sample, check its list of siblings to check if the sample has already pushed and merge with that instead of allocating a new one.
* Samples need a new field that keeps track of the number of times they're called.
* Need to add a new column to the viewer for call count.

It's actually quite a simple task. I've just not added it yet as I've not needed it.

Note the same can also be said for recursion, although recursion is a lot easier to check for

**Comment by dwilliamson** [comment]
No, all samples are unique and don't collapse or recognise recursion. By default, aggregating samples is not optimal behaviour for an instrumenting sampler and Remotery's first goal is to interfere with your timings as little as possible.

However, this goal is not good enough on its own. Remotery needs the ability to do what you ask and the place to insert that feature is here: https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L3408

In short, this needs to happen:

    Public API needs to support sample flags or different function calls for samples that aggregate.
    When pushing a sample, check its list of siblings to check if the sample has already pushed and merge with that instead of allocating a new one.
    Samples need a new field that keeps track of the number of times they're called.
    Need to add a new column to the viewer for call count.

It's actually quite a simple task. I've just not added it yet as I've not needed it.

Note the same can also be said for recursion, although recursion is a lot easier to check for

**Comment by Scraft** [comment]
For what it is worth, I'd like to see this feature too...

**Comment by jswigart** [comment]
Looking at this briefly even though it doesn't look difficult to look up the matching name hash and such, it's unclear to me what the preferred method of implementing the other aspects of it.

If the samples are not called in rapid succession, you lose the ordering somewhat by combining them into a count, so perhaps a mixed approach would be preferable, where all of the same samples names are combined only with matching adjacent sample names, so you don't lose sample ordering.

So something like this
Sample1
Sample1
Sample1
Sample1
Sample2
Sample1

would become
Sample1   count4 with combined timings
Sample2   count0
Sample1   count1

That way you don't lose the sample ordering but you reduce the publication traffic to the socket, and that reduces the complexity of this change, bc since the samples are tracked and published by start and end time, combining samples that arent adjacent would seem like an issue. Perhaps it still is, because I'm guessing theres no guarantee that adjacent samples of the same name should not have a hole in between them in the timeline. Maybe adjacent combined samples are published under 1 sample name and N number of start/end times so that holes are still visualized, but in the sample window for a particular scope it can still be a single name and count entry in the tree view.

At the end of the day this is largely meant to be a bloat reduction in the data output and the

**Comment by dwilliamson** [comment]
Yes, the implementation is quite easy and the [code already checks for nearby merging](https://github.com/Celtoys/Remotery/blob/master/lib/Remotery.c#L3512).

The difficulty is in coming up with a public API that:

* Only triggers this behaviour on a flag.
* Allows other flags to be specified (e.g. collapse recursion? linear search merge?).
* Allows auto-named samples, as well as string-sourced sample names.
* Easily allows more platforms beyond CPU, D3D11, CUDA, etc.

Keeping the surface area as small as possible and not requiring constant changes for the people currently using it is important. We're going to have to do this once to get all these features above in so some ideas on how to solve all that are welcome.

**Comment by dwilliamson** [comment]
While looking at this I've come up against another issue: how is collapsing represented in the timeline?

Suppose you have (name, start time, length, calls):

```
A,2,3,1
B,5,2,1
A,7,2,1
B,9,4,1
```

This is easily represented in the sample view with:

```
A,2,5,2
B,5,6,2
```

But now there's overlap between A and B. Leaving this alone would mean they'd render on top of each other in the timeline.

One option is to make sure, when rendering the timeline, to look at the previous sibling and shift the start point to its max while maintaining length. While this works, it no longer represents an accurate overview of the call sites.

What happens when a call pops up in-between?

```
A,2,3,1
B,5,2,1
C,7,1,1
A,8,2,1
B,10,4,1
```

C is now out-of-order with the collapsed samples. Maybe that's acceptable

Maybe the collapse could occur in the viewer instead of in the profiler. The timeline view could show you each point of call accurately while the sample view would show you the collapsed sum with a toggle option. This would be really neat but it's not solving any of the runtime/network performance issues we have from issuing highly frequent calls that need merging on the client.

That then leads onto the case of network compression: we could reasonably achieve this if the JSON was more compact or there was some binary in there.

Or another way of looking at this: only allow merging with immediate siblings. This maintains order and does not broadcast too much data. If you have a sequence that you want to have bits merged you'd need to parent them; so:

```
A
B
A
B
```

becomes:

```
C
   A
   B
C
   A
   B
```

C gets collapsed and A and B are merged internally. This requires a little bit more thought on behalf of the programmer.

I don't know. It seems the best path to follow for now is the first one and accept that the timeline and order within a set of collapsed siblings won't be accurate. Then at a later point, compress the heck out of the network stream and do the collapse optionally on the client.

All of this really does reinforce the need for per sample config flags.

**Comment by jswigart** [comment]
Honestly, if the bandwidth requirements can be reduced to the extent that it's not so easily flooded into breaking, it doesn't need to collapse anything on the profiler side at all as far as I care, and the focus can be put in the viewer code to improve the presentation of those huge outputs. I think you're going to need to move to something that is more binary encoded though, and do things like sending a table of contents string table so that the sample data isn't so bloated with string data and such.

Where I was getting with my last comment was that in order to preserve enough information to reconstruct the ordering(and in a way that hopefully reduces the bandwidth) they might be combined into a sample structure like 

(name, start time, length, start time2, length2, ...N ):

And with that, it's 1 sample to the profiler, but it has the full ordering and time spans of each iteration of it, and other samples may fill in gaps in that timing data. 

So your ABC example becomes(leaving off the calls field), brackets added per 'call'
A,[2,3],[8,2]
B,[5,2],[10,4]
C,7,1

I think the first step ought to be general purpose efficiency refactoring of the data stream to get the data sizes way down. Text based json streams is really not great for high volume.

**Comment by dwilliamson** [comment]
I'm on a project right now that is sending 100s of samples of up to 30 threads so expect network compression to become a bit of a priority very soon.

**Comment by dwilliamson** [comment]
Added sample aggregation in https://github.com/Celtoys/Remotery/commit/5b3f1ddb1995747ab9c0108c2b57a75542ec7d56

To be honest, I'm calling the timeline view a user-issue for now unless somebody comes up against a problem that's obstructing them. My thoughts above have been over-complicating things: just don't mix aggregate/non-aggregate samples in the same parent!
