### ISSUE TITLE
OSX: Missing NSGLGetProcAddress

### ISSUE THREAD

**Issue by bkaradzic** [Celtoys/Remotery#72]
I had to make workaround missing NSGLGetProcAddress function in newer OSX.
https://github.com/bkaradzic/bgfx/commit/c3dd88767a8642e030916527937624a27cf3b3eb

**Comment by alpha-xue** [comment]
@bkaradzic May I ask some question about this repository?

**Comment by pjohalloran** [comment]
Hi @dwilliamson and @bkaradzic,

I am seeing the same issue on Xcode 8.2, Apple LLVM 8.0 in a side project i am working on.
As a quick test, I changed the Remotery code to use GLFW extension fetching functions and its all good with that, but of course you dont want a dependency on a library like that in Remotery.
Not sure if other OSX users are seeing this issue also.

@bkaradzic you have used dlopen to solve the problem. I notice that there is already code for Window, posix systems in Remotery that uses dlopen also. Maybe Don, you would consider looking over a pull request for a fix (using the dlopen code path already in the code)? I can volunteer to prepare a patch for you.

Thanks,
PJ

**Comment by pjohalloran** [comment]
I see there is some discussion ongoing at the moment in this area https://github.com/Celtoys/Remotery/issues/68. Just saw after posting, not sure if my proposal makes sense if you guys are refactoring this area atm.

**Comment by pjohalloran** [comment]
See PR on a fork for details on changes i made based on @bkaradzic commit mentioned above.
https://github.com/pjohalloran/Remotery/pull/1/files
Tested in my side project and works but can close it in favor of a better fix or tidy up based on your feedback.

**Comment by dwilliamson** [comment]
Thanks for showing an interest in fixing this.

So my understanding of this problem has waned since I last looked at it. I believe OpenGL can be found in multiple places other than `/System/Library/Frameworks/OpenGL.framework/Versions/Current/OpenGL` and that's why `NSGLGetProcAddress` was an exercise left to the reader.

At the very least, I've seen code in other libraries that can search for the installed OpenGL location.

If we had to choose between these two:

1. All users get the `NSGLGetProcAddress` compile error before being able to use Remotery.
2. No users get an error, OpenGL just silently fails to load for a subset of users. Users must edit code to their location.

I would rather we had 1. Your fix looks clean but I'm afraid of it only working silently for a subset of users.

**Comment by dwilliamson** [comment]
Oh, bear in mind this would ideally work for OSX and iOS.

**Comment by pjohalloran** [comment]
I'm not sure why im seeing this issue to be honest as i am linking to the OpenGL framework in xcode but it can't find `NSGLGetProcAddress` at linking stage. 

Thats cool yeah. That example in my branch will def not work on iOS. I am looking into how GLFW does it. It uses `CFBundleGetBundleWithIdentifier` which i'd imagine should work on iOS rather than a hardcoded path. I dont think current release of GLFW runs on iOS so would have to test that.
See: https://github.com/glfw/glfw/blob/master/src/nsgl_context.m line 98.

I can update my branch with how its done there and see if it works and do a test on a small iOS project also (simulator only as am not setup to build to device at home). Does that sound better ?

**Comment by pjohalloran** [comment]
Updated PR with usage of `CFBundleGetBundleWithIdentifier`. Tested on osx, need some more time to test on iOS.

**Comment by dwilliamson** [comment]
`NSGLGetProcAddress` doesn't actually exist and Remotery expects the user to implement it due to the complexity of this problem on OSX/iOS. An example implementation can be found https://github.com/mini3d/mini3d/blob/6d769efb75096a4f960cd0afaf824f194f7b2e04/mini3d_graphics/opengl/platform/osx/openglwrapper_osx.cpp#L23 (I believe this is copied almost verbatim from Steamworks).

If your code works for stock OSX then I'm willing to include it as long as iOS somehow retains the existing behaviour of creating a link error.

**Comment by pjohalloran** [comment]
Ahhhhhh :) Makes total sense now. It sounded like an official apple helper function for OpenGL extension loading.

I can do a test on a device next week when back in work. If it works for both iOS and OSX might be worth including it. I'll get back to you on it.

**Comment by pjohalloran** [comment]
Update: this doesnt work on iOS, sorry to have gone off topic, i misunderstood the original issue. I think maybe best to keep it as `NSGLGetProcAddress`.

**Comment by dwilliamson** [comment]
Thanks for all feedback on this. Latest version will use rmtLoadLibrary to no longer require on an external function.
